export const RoutePath = {
  HOME: "/",
  AUTH: "auth",
  LOGIN: "login",
  REGISTER: "register",
  OTP: "otp",
  ENTER_EMAIL: "enter_email",
  RESET_PASSWORD: "reset_password",
  CLIENT: "client",
  FREELANCER: "freelancer",
  CREATE_POST: "create-job",
  CLIENT_HOME: "client_home",
  LOGOUT: "logout",
  GET_POSTS: "get-posts",
  GET_MY_POSTS: "get-my-posts",
  SINGLE_POST: "single-post",
  MY_POST: "my-post",
  EDIT_POST: "edit-post",
  SEND_PROPOSAL: "send-proposal",
  GET_MY_PROPOSALS: "get-my-proposals",
  GET_PROPOSALS_BY_POST: "get-post-proposals",
  MY_PROPOSAL: "my-proposal",
  CREATE_CONTRACT: "create-contract",
  SINGE_PROPOSAL: "single-proposal",
  GET_MY_CONTRACTS: "get-my-contracts",
};

//export type RoutePath = (typeof RoutePath)[keyof typeof RoutePath];
